#!/usr/bin/env python3
"""Build per-episode feature files from cached transcripts.

Pipeline per transcript:
  1. Strip YouTube auto-caption noise ([Music], [Applause], uh, um, ...)
  2. Lowercase + tokenize on word boundaries
  3. Remove stopwords (NLTK English list)
  4. Stem with Porter stemmer
  5. Compute token frequency

Output: episodes/{id}/features.json
  {
    "video_id": "...",
    "token_freq": {"fight": 42, "sport": 31, ...},
    "top_tokens": [["fight", 42], ...],   // top 50
    "token_count": 1234
  }

Usage:
    uv run python scripts/build_features.py
    uv run python scripts/build_features.py --video-id MtoPEub7XwA
    uv run python scripts/build_features.py --limit 100
    uv run python scripts/build_features.py --force   # re-process existing features
"""

import argparse
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

import cache as cache_mod

nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)

_STEMMER = PorterStemmer()
_STOPWORDS = set(stopwords.words("english"))

# ── All English pronouns ───────────────────────────────────────────────────────
_PRONOUNS = {
    # personal
    "i",
    "me",
    "my",
    "mine",
    "myself",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "we",
    "us",
    "our",
    "ours",
    "ourselves",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    # demonstrative
    "this",
    "that",
    "these",
    "those",
    # relative / interrogative
    "who",
    "whom",
    "whose",
    "which",
    "what",
    # indefinite
    "one",
    "ones",
    "someone",
    "somebody",
    "something",
    "anyone",
    "anybody",
    "anything",
    "everyone",
    "everybody",
    "everything",
    "noone",
    "nobody",
    "nothing",
    "each",
    "either",
    "neither",
    "both",
    "few",
    "several",
    "many",
    "much",
    "more",
    "most",
    "other",
    "others",
    "another",
    "any",
    "all",
    "none",
    "some",
    "such",
}

# ── Base-vocabulary verbs (A1–A2 learner word lists) ─────────────────────────
# High-frequency, low-specificity — present in every episode regardless of topic
_BASE_VERBS = {
    # modals
    "can",
    "could",
    "will",
    "would",
    "shall",
    "should",
    "may",
    "might",
    "must",
    "ought",
    "be",
    "is",
    "are",
    "was",
    "were",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "done",
    "doing",
    "say",
    "said",
    "says",
    "saying",
    "go",
    "goes",
    "went",
    "gone",
    "going",
    "get",
    "gets",
    "got",
    "gotten",
    "getting",
    "make",
    "makes",
    "made",
    "making",
    "know",
    "knows",
    "knew",
    "known",
    "knowing",
    "think",
    "thinks",
    "thought",
    "thinking",
    "take",
    "takes",
    "took",
    "taken",
    "taking",
    "see",
    "sees",
    "saw",
    "seen",
    "seeing",
    "come",
    "comes",
    "came",
    "coming",
    "want",
    "wants",
    "wanted",
    "wanting",
    "look",
    "looks",
    "looked",
    "looking",
    "use",
    "uses",
    "used",
    "using",
    "find",
    "finds",
    "found",
    "finding",
    "give",
    "gives",
    "gave",
    "given",
    "giving",
    "tell",
    "tells",
    "told",
    "telling",
    "work",
    "works",
    "worked",
    "working",
    "call",
    "calls",
    "called",
    "calling",
    "try",
    "tries",
    "tried",
    "trying",
    "ask",
    "asks",
    "asked",
    "asking",
    "need",
    "needs",
    "needed",
    "needing",
    "feel",
    "feels",
    "felt",
    "feeling",
    "become",
    "becomes",
    "became",
    "becoming",
    "leave",
    "leaves",
    "left",
    "leaving",
    "put",
    "puts",
    "putting",
    "mean",
    "means",
    "meant",
    "meaning",
    "keep",
    "keeps",
    "kept",
    "keeping",
    "let",
    "lets",
    "letting",
    "begin",
    "begins",
    "began",
    "begun",
    "beginning",
    "show",
    "shows",
    "showed",
    "shown",
    "showing",
    "hear",
    "hears",
    "heard",
    "hearing",
    "play",
    "plays",
    "played",
    "playing",
    "run",
    "runs",
    "ran",
    "running",
    "move",
    "moves",
    "moved",
    "moving",
    "live",
    "lives",
    "lived",
    "living",
    "hold",
    "holds",
    "held",
    "holding",
    "bring",
    "brings",
    "brought",
    "bringing",
    "happen",
    "happens",
    "happened",
    "happening",
    "write",
    "writes",
    "wrote",
    "written",
    "writing",
    "sit",
    "sits",
    "sat",
    "sitting",
    "stand",
    "stands",
    "stood",
    "standing",
    "lose",
    "loses",
    "lost",
    "losing",
    "pay",
    "pays",
    "paid",
    "paying",
    "meet",
    "meets",
    "met",
    "meeting",
    "set",
    "sets",
    "setting",
    "learn",
    "learns",
    "learned",
    "learning",
    "change",
    "changes",
    "changed",
    "changing",
    "lead",
    "leads",
    "led",
    "leading",
    "understand",
    "understands",
    "understood",
    "understanding",
    "watch",
    "watches",
    "watched",
    "watching",
    "follow",
    "follows",
    "followed",
    "following",
    "stop",
    "stops",
    "stopped",
    "stopping",
    "speak",
    "speaks",
    "spoke",
    "spoken",
    "speaking",
    "read",
    "reads",
    "reading",
    "spend",
    "spends",
    "spent",
    "spending",
    "grow",
    "grows",
    "grew",
    "grown",
    "growing",
    "open",
    "opens",
    "opened",
    "opening",
    "walk",
    "walks",
    "walked",
    "walking",
    "remember",
    "remembers",
    "remembered",
    "remembering",
    "love",
    "loves",
    "loved",
    "loving",
    "appear",
    "appears",
    "appeared",
    "appearing",
    "wait",
    "waits",
    "waited",
    "waiting",
    "send",
    "sends",
    "sent",
    "sending",
    "build",
    "builds",
    "built",
    "building",
    "stay",
    "stays",
    "stayed",
    "staying",
    "fall",
    "falls",
    "fell",
    "fallen",
    "falling",
    "cut",
    "cuts",
    "cutting",
    "reach",
    "reaches",
    "reached",
    "reaching",
    "remain",
    "remains",
    "remained",
    "remaining",
    "suggest",
    "suggests",
    "suggested",
    "suggesting",
    "pass",
    "passes",
    "passed",
    "passing",
    "sell",
    "sells",
    "sold",
    "selling",
    "decide",
    "decides",
    "decided",
    "deciding",
    "pull",
    "pulls",
    "pulled",
    "pulling",
    "talk",
    "talks",
    "talked",
    "talking",
    "start",
    "starts",
    "started",
    "starting",
    "help",
    "helps",
    "helped",
    "helping",
    "turn",
    "turns",
    "turned",
    "turning",
    "buy",
    "buys",
    "bought",
    "buying",
    "serve",
    "serves",
    "served",
    "serving",
    "kill",
    "kills",
    "killed",
    "killing",
    "raise",
    "raises",
    "raised",
    "raising",
    "carry",
    "carries",
    "carried",
    "carrying",
    "break",
    "breaks",
    "broke",
    "broken",
    "breaking",
    "eat",
    "eats",
    "ate",
    "eaten",
    "eating",
    "drink",
    "drinks",
    "drank",
    "drunk",
    "drinking",
    "sleep",
    "sleeps",
    "slept",
    "sleeping",
    "hit",
    "hits",
    "hitting",
    "seem",
    "seems",
    "seemed",
    "seeming",
    "believe",
    "believes",
    "believed",
    "believing",
    "imagine",
    "imagines",
    "imagined",
    "imagining",
    "wonder",
    "wonders",
    "wondered",
    "wondering",
    "guess",
    "guesses",
    "guessed",
    "guessing",
    "suppose",
    "supposes",
    "supposed",
    "supposing",
    "reckon",
    "reckons",
    "reckoned",
    "reckoning",
    "like",
    "likes",
    "liked",
    "liking",
}

# ── Base-vocabulary adverbs (A1–A2) ──────────────────────────────────────────
_BASE_ADVERBS = {
    "very",
    "really",
    "quite",
    "just",
    "also",
    "still",
    "even",
    "often",
    "always",
    "never",
    "sometimes",
    "already",
    "now",
    "then",
    "here",
    "there",
    "soon",
    "again",
    "well",
    "back",
    "too",
    "more",
    "most",
    "only",
    "much",
    "less",
    "both",
    "far",
    "long",
    "little",
    "enough",
    "so",
    "up",
    "out",
    "away",
    "down",
    "together",
    "first",
    "next",
    "last",
    "early",
    "late",
    "quickly",
    "slowly",
    "hard",
    "fast",
    "almost",
    "usually",
    "probably",
    "maybe",
    "perhaps",
    "however",
    "therefore",
    "actually",
    "basically",
    "literally",
    "simply",
    "exactly",
    "especially",
    "finally",
    "recently",
    "immediately",
    "directly",
    "completely",
    "suddenly",
    "nearly",
    "hardly",
    "mostly",
    "clearly",
    "once",
    "twice",
    "else",
    "anyway",
    "instead",
    "ahead",
    "around",
    "behind",
    "across",
    "though",
    "yet",
    "definitely",
    "certainly",
    "absolutely",
    "totally",
    "pretty",
    "kinda",
    "sorta",
}

# ── Base-vocabulary adjectives (A1–A2) ───────────────────────────────────────
_BASE_ADJECTIVES = {
    "good",
    "bad",
    "big",
    "small",
    "large",
    "little",
    "new",
    "old",
    "long",
    "short",
    "high",
    "low",
    "great",
    "hard",
    "easy",
    "free",
    "real",
    "right",
    "wrong",
    "different",
    "possible",
    "important",
    "young",
    "full",
    "open",
    "hot",
    "cold",
    "warm",
    "dark",
    "light",
    "same",
    "similar",
    "common",
    "certain",
    "ready",
    "strong",
    "weak",
    "true",
    "false",
    "fine",
    "nice",
    "simple",
    "sure",
    "clear",
    "whole",
    "every",
    "happy",
    "sad",
    "fast",
    "slow",
    "early",
    "late",
    "rich",
    "poor",
    "quiet",
    "loud",
    "clean",
    "dirty",
    "safe",
    "dangerous",
    "fresh",
    "dead",
    "alive",
    "busy",
    "empty",
    "heavy",
    "wide",
    "narrow",
    "deep",
    "flat",
    "round",
    "straight",
    "close",
    "far",
    "local",
    "general",
    "public",
    "special",
    "second",
    "third",
    "own",
    "next",
    "last",
    "another",
    "other",
    "able",
    "crazy",
    "weird",
    "cool",
    "awesome",
    "horrible",
    "terrible",
    "amazing",
    "interesting",
    "boring",
    "funny",
    "serious",
    "stupid",
    "smart",
    "beautiful",
    "ugly",
    "pretty",
    "normal",
    "strange",
    "odd",
}

# ── Spoken filler & JRE-specific noise ───────────────────────────────────────
_SPOKEN_NOISE = {
    "yeah",
    "yep",
    "nope",
    "okay",
    "oh",
    "ah",
    "hey",
    "wow",
    "hmm",
    "uh",
    "um",
    "gonna",
    "wanna",
    "gotta",
    "cuz",
    "cause",
    "thing",
    "stuff",
    "way",
    "lot",
    "guy",
    "guys",
    "man",
    "dude",
    "bro",
    "sort",
    "kind",
    "bunch",
    "type",
    "bit",
    "piece",
    "whatever",
    "whenever",
    "wherever",
    "whoever",
    "however",
    "joe",
    "rogan",
    "podcast",
    "show",
    "episode",
    "guest",
    "interview",
    "people",
    "person",
    "time",
    "year",
    "day",
    "week",
    "ago",
    "something",
    "anything",
    "everything",
    "nothing",
}

# Merge all, stem, build final set
_ALL_RAW = _PRONOUNS | _BASE_VERBS | _BASE_ADVERBS | _BASE_ADJECTIVES | _SPOKEN_NOISE
_EXTRA_STEMS = {_STEMMER.stem(w) for w in _ALL_RAW}
_ALL_STOPWORDS = _STOPWORDS | _EXTRA_STEMS

# YouTube auto-caption artifacts to strip before tokenizing
_NOISE_RE = re.compile(
    r"\[(?:music|applause|laughter|inaudible|crosstalk|silence)\]"
    r"|\b(?:uh|um|uhh|umm|hmm|gonna|wanna|gotta|kinda|sorta)\b",
    re.IGNORECASE,
)
_TOKEN_RE = re.compile(r"[a-z]{3,}")  # only alpha tokens, min length 3


def process_transcript(text: str) -> dict:
    cleaned = _NOISE_RE.sub(" ", text).lower()
    tokens = _TOKEN_RE.findall(cleaned)
    tokens = [_STEMMER.stem(t) for t in tokens if t not in _ALL_STOPWORDS]
    tokens = [t for t in tokens if t not in _EXTRA_STEMS]  # post-stem filter
    freq = Counter(tokens)
    return {
        "token_freq": dict(freq.most_common()),
        "top_tokens": freq.most_common(50),
        "token_count": len(tokens),
    }


def _default_cache_dir() -> Path:
    env = os.environ.get("YT_CACHE_DIR")
    return Path(env) if env else Path(__file__).parent.parent / "cache"


def main():
    parser = argparse.ArgumentParser(description="Build feature files from cached transcripts")
    parser.add_argument("--cache-dir", type=Path, default=None)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--video-id", action="append", dest="video_ids")
    parser.add_argument(
        "--force", action="store_true", help="Re-process even if features.json exists"
    )
    args = parser.parse_args()

    cache_dir = args.cache_dir or _default_cache_dir()
    if not cache_dir.exists():
        print(f"Cache not found: {cache_dir}")
        return 1

    index = cache_mod.read_index(cache_dir)
    if not index:
        print("Index is empty.")
        return 1

    if args.video_ids:
        targets = [e for e in index if e["video_id"] in args.video_ids]
    else:
        targets = [e for e in index if cache_mod.has_transcript(cache_dir, e["video_id"])]
        if not args.force:
            targets = [
                e
                for e in targets
                if not (cache_mod.episode_dir(cache_dir, e["video_id"]) / "features.json").exists()
            ]

    if args.limit:
        targets = targets[: args.limit]

    print(f"Cache: {cache_dir}")
    print(f"Processing {len(targets)} episodes")
    print()

    done = 0
    for i, entry in enumerate(targets, 1):
        vid = entry["video_id"]
        transcript = cache_mod.read_transcript(cache_dir, vid)
        if not transcript:
            continue

        result = process_transcript(transcript)
        result["video_id"] = vid

        feat_path = cache_mod.episode_dir(cache_dir, vid) / "features.json"
        feat_path.write_text(json.dumps(result, indent=2, ensure_ascii=False, encoding="utf-8"))
        done += 1

        if i % 50 == 0 or i == len(targets):
            print(f"  [{i}/{len(targets)}] {done} processed", flush=True)

    print(f"\nDone. Built features for {done} episodes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
